language: python
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
install:
- pip install rst2pdf
script:
- rst2pdf ./crw/safety_and_engineering_binder.rst ./crw/crw_safety_and_engineering_binder.pdf
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jooQLZCH7oIjSnCEElk+BcakIy9VN3HYQYsQnaDJxnJcDI1uj1g0ysHB9McgFm9XnNMLsGT4X6D2zDbloOIJBtSmocagN7Zv3SxOfTn9lMHpePzr6SmjsomonaQiJXNydg7zjx6uLey/vBDtuZz9Ed6WLdkX2BUBL8ArDupMACGmikFmzM1vq09kFwbJPBLou5m7gnXLpfDi9TeO/otLxq/iWzT+LySAX4AjZ7M4867uHPjFDfHBXghGLRW4yEPYzzsGy6BUCVbsM6f0lQ1V8iPrftm/HYS38fmyf2tidtDv9rNZULpHZvpTb/yoPDJxUM5JPpC6Owb4t7y8CAlP8WNgzdXjjYhxvsyOJNk1z+ensIrIgbIYbzkmBNRdFK2Xv1V1At7AqCkARMqdDz/z8iEx2Nv/bxmZLkqqG9WrZWIGNEfhu1rJUDfGLzT8ldXc0x9L6QZ7VObrbmtvSP0Dv+BS5xHzhYFaaECWyXboWWe250aPqwRsG8H95WMZU4Aao+Ei8Egy9eOhlVkIt1/rnwCGCIj5eVhT7qoVhOSPZNF7jSM3sA0GOsQlX6LYtIx+Tq2bHBDLINqy6Ku4ZaoYwbFBYn6BTWZg+DysPTYbg+5vFp60mIuBjiQ0iUYWzVoH7/AzaxFDMy5sc+1s4Hr6a4pVLQZps53GWPA8LkIE2tg=
  file:
  - crw/crw_safety_and_engineering_binder.pdf
  on:
    repo: memhamwan/deployment-engineering
    tags: true
notifications:
  slack:
    secure: VO1jEsjLs7RR5UTTc0O4YRUECeXLnVitxhEYAt0Zb6C6QgzuCE93nbCW+igjpIixBtG1tbZ8XCib7d41KGS91NqQMRsPe71o7tCWvZLM+eadOufj0zu0pwVSSW3r1K7YWsqwKgsyO//3hhIFAAqVtSU1LU451BzuXv3oi9NtjprcpaAWhLUotFc+g62DMOSxQHn0+95gNl1/Jj94RbvP0ODfL1Gqd0GLNifi8cmDY/fBKDEZVp1n7m3ZReqg0PvQ8ww3IZP4q7N4fbQB4At6h62v77SUew2mpObFpXl6bJP6c6QKPxGSXDGWBFTq3AYqtncfNfaTF0YxM6aYPKiH63m2v537GPSSwj+yvmo87t/N9lIQy3YLF3tK2sS4bQ25FYiq32wISfNbjapcujbuYQXWFsGK0HViDXESjZgcxbX7J5IBEMJPxZXZL8S4sxDl3twg3/ionrzdZwGSNnuhWKLEsUJwMF3Fj2hLlwIx3yOZKB9+CPmt21OpRFHkrSl7YQrP35Dy8NwPwbykynI9TgJC58IL1Q0KDYQkj3l1VLxDDBrzWQp2UHNDxe03kjQLjksg9sbFqTXZziUc0nS0bIr8g20JhnPh3SR3A7XMojnSXQI2bqNDPGOj/Of1TD8ulorEpS3/QVsPRw1juxQpwPOkx/ghr/M4+Bfk/0rvMsg=
